#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
#Browser Configuration
browser = chrome

#Credentials
username = admin
password = admin123

#ImplicitWait (in seconds)
implicitwait = 15

#ExplicitWait
explicitwait = 30